version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: looksrare-worker
    env_file:
      - .env
volumes:
  notused: